# You can freely (re)use this GitLab template to enable CI (Continuous Integration) for your own open font project.
# Your project needs to make use of smith. See https://github.com/silnrsi/smith
# For documentation on the recommended steps see Font Development Best Practises at http://silnrsi.github.io/FDBP
# More details in the GitLab documentation at https://docs.gitlab.com/ce/ci/README.html
# Enjoy and let us know if you find issues. 

default:
  image: "ubuntu:focal"

stages:
  - build
  - test

variables:
  DEBIAN_FRONTEND: noninteractive
  TZ: Etc/UTC

smith:
  stage: build
  before_script:
    - apt-get update -q -y
    - apt-get install -q -y tzdata software-properties-common libterm-readline-gnu-perl python3-pip
    - add-apt-repository -y ppa:silnrsi/smith-py3
    - add-apt-repository -y ppa:git-core/ppa
    - add-apt-repository -y ppa:sile-typesetter/sile
    - apt-get update -q -y
    - apt-get install -q -y sile python3-odf python-odf-tools libjson-perl libtext-csv-perl libharfbuzz-bin
    - apt-get install -q -y --no-install-recommends smith-font
    - pip install fontbakery
    - git config --global safe.directory $PWD
  script:
    - smith configure
    - smith build
    - smith alltests
    - smith ttfchecks
    - smith zip
    - smith tarball
    - smith release 
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}${CI_COMMIT_SHA:0:8}-build${CI_JOB_ID}"
    paths:
    - results/releases/*
    - results/*.html
    - results/*.pdf
    - results/*.txt
    - results/*err*
    - results/tests/*

fontproof:
  stage: test
  image:
    name: ghcr.io/sile-typesetter/fontpfoof:v2
    entrypoint: [""] # default entrypoint is fontproof itself, not a shell
  needs:
    - job: smith
  script:
    - |
      for ttf in results/*.ttf; do
        fontproof -f $ttf -o FontProof-$(basename ${ttf%.ttf}).pdf -- tests/Latin.sil
      done
  artifacts:
    paths:
      - FontProof-*.pdf
